baseurl = "/"
languageCode = "en-us"
title = "Geographer In Nature"
defaultContentLanguage = "en"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-117542884-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Hi! I'm Hyesop, an indoor Geographer working on social models."
  footer = "All the writings and figures are under my copyright."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-01"
  codePenUser = "someUser"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  #[[menu.nav]]
  #  name = "About"
  #  url = "/about/"
  #  weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
