baseurl = "/"
languageCode = "en-us"
title = "Geographer In Nature"
defaultContentLanguage = "en"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-117542884-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", ".DS_Store"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Geography, Models, Football, and Coffee. *Currently @UK*. <br> Words are my own"
  footer = "Works under the MIT License. Hyesop 2019."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-01"
  codePenUser = "someUser"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Research"
    url = "/research"
    weight = 2
  [[menu.nav]]
    name = "R-blog"
    url = "/post/"
    weight = 3
  [[menu.nav]]
    name = "Pictures"
    url = "/pics/"
    weight = 4
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 5
#  [[menu.nav]]
#    name = "RSS"
#    url = "/index.xml"
#    weight = 5
