baseurl = "/"
languageCode = "en-us"
title = "Geographer In Nature"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-117542884-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "hs621@cam.ac.uk"
    facebook = "shinhyesop"
    twitter = "hyesop"
    #dribbble = "alexiscollado"
    #linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"
    #medium = "ahvccollado"
    github = "mrsensible"
    #googlescholar = "https://scholar.google.com/citations?user=XXXXXXXXXXXXXXXXXXXXX=en"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Hyesop, an indoor Geographer working on social models."
    hero_right = ["**Currently doing a Ph.D in Geography**", "I am writing", "Here is my [data storage](https://seoul.netlify.com)"]
    #resume = "CV.md"

[params.process]
    enable = true
    title = "My Interests"
    subtitle = "Geographer"

[params.case_studies]
    enable = true
    title = "Posts"
    subtitle = "Writing about codes and ideas"



[params.footer]
    enable = true
